services:
  postgres:
    image: postgres:16
    container_name: cex-postgres
    environment:
      POSTGRES_DB: cex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - cex_postgres_data:/var/lib/postgresql/data

volumes:
  cex_postgres_data: